name: Github Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Change the structure
        run: |
          mv README.md index.md
          mv mkdocs.yml ../
          ls
        
